#!/bin/sh

ME=~/Private/conf/me
MAIL=$1

get_header()
{
    grep -m1 -i "^$1:" $MAIL | cut -f1 -d' ' --complement | sed -r 's/.*<(.*)>.*/\1/'
}

ask()
{
    local input=$(eval "echo \$$2")
    local as_is="${input//\./\\.}"
    as_is="${as_is//\+/\\+}"

    local domain=".*$(echo "$as_is" | grep -o '@.*$')"
    local temp=$(mktemp)

    dialog --inputmenu \
        "Adding $1 for $input.\n\nWhat would you like to do?" \
        16 90 13 \
        "As Is" "$as_is" \
        "Domain Only" "$domain" \
        2>> $temp

    local ans=$(cat $temp)
    rm $temp
    
    case $ans in
        "As Is")
            eval "$2='$as_is'" ;;
        "Domain Only")
            eval "$2='$domain'" ;;
        *)
            eval "$2='$(echo $ans | cut -f4 -d' ')'" ;;
    esac
}

from=$(get_header 'From')
to=$(get_header 'Delivered-To')
msg_id=$(get_header 'Message-ID')

ask rule to
ask exemption from

to_clean=$(echo $to | sed -e 's/[]\/$*.^|[]/\\&/g')
from_clean=$(echo $from | sed -e 's/[\/&]/\\&/g')
temp=$(mktemp)

sed -r "s/^$to_clean .*\$/&|$from_clean/" $ME > $temp

if ! diff -q $temp $ME
then
    cp -f $tmp $ME
else
    echo "$to $from" >> $ME
fi

rm $temp
