#!/bin/sh

# Run notmuch, ignoring error messages about mbsync's state files
notmuch new 2>&1 | grep -vP '\.(uid|mbsync)' >&2

notmuch tag -new +private -- tag:new folder:Private
notmuch tag -new +bounces -- tag:new folder:Bounces
notmuch tag -new +sent    -- tag:new folder:Sent

# Do not pop these up
notmuch tag -new -- tag:new and folder:Junk

notmuch search --format=json tag:new | ~/.dotfiles/sbin/mail/new_popup
notmuch tag -new +inbox -- tag:new

# We're done, refresh the menubar
pkill -RTMIN+1 i3blocks
