#!/bin/sh

regex='((http|https|ftp|gopher|mailto)[.:][^ >"\t]*|www\.[-a-z0-9.]+)[^ \]*.,;\t>">\):]'
list=$(mktemp)
temp=$(mktemp)

for url in $(grep -oP "$regex")
do
    if [[ "${url%%:*}" == "$url" ]]
    then
        if [[ "${url%%@*}" == "$url" ]]
        then
            url="http://$url"
        else
            url="mailto:$url"
        fi
    fi

    if echo $url | grep -i '^[a-z]\+://[^/]*$'
    then
        url="$url/"
    fi

    echo $url >> $list
done

dialog --no-shadow --inputmenu "Choose link to open" \
    200 250 200 \
    $(sort -u $list | awk '{printf("%d %s\n", NR, $0)}') 2> $temp

if test $? -eq 1
then
    exit 0
fi

if test "$(cat $temp | cut -f1 -d' ')" == "RENAMED"
then
    id=$(cat $temp | cut -f1,2 -d' ' --complement)
else
    id=$(cat $temp | cut -f1 -d' ')
    id=$(cat $list | grep "^$id " | cut -f1 -d' ' --complement)
fi

rm $temp $list

xdg-open $id

