#!/bin/php
<?php

foreach (json_decode(`notmuch search --format=json tag:new`) as $mail)
{
    $subject = $mail->subject;
    $from    = trim(explode('|', $mail->authors)[0]);

    `notify-send "New Mail From: $from" "$subject"`;
}
