#!/bin/sh

cat <<EOF
virtual-mailboxes \\
    "INBOX" "notmuch://?query=folder:INBOX" \\
    "Starred" "notmuch://?query=tag:*" \\
    "Unread" "notmuch://?query=tag:unread" \\
EOF

for list in $(ls ~/Private/mail | grep -P '^ML\.')
do
    domain=$(echo $list | sed -r 's/\.[^.]+$//')

    if ! test "$domain" == "$last_domain"
    then
        domainlist=${domain:3}
        domainlist=${domainlist//-/.}
        last_domain=$domain

        echo "\"$domainlist\" \"$domainlist\" \\"
    fi

    name=$(echo $list | sed -r 's/ML\.[^.]+\.//')
    echo "\"  $name\" \"notmuch://?query=folder:$list\" \\"
done

cat <<EOF
    "Private" "notmuch://?query=folder:Private" \\
    "Sent" "notmuch://?query=folder:Sent" \\
    "Junk" "notmuch://?query=folder:Junk" \\
    "Archived" "notmuch://?query=folder:Archive"
EOF
