#!/bin/sh

notmuch new
notmuch tag -new +private -- tag:new folder:Private
notmuch tag -new +bounces -- tag:new folder:Bounces

# Do not pop these up
notmuch tag -new -- tag:new and \( folder:Sent or folder:Junk \)

notmuch search --format=json tag:new | ~/.dotfiles/sbin/mail/new_popup
notmuch tag -new +inbox -- tag:new

# We're done, refresh the menubar
pkill -RTMIN+1 i3blocks
