#!/bin/sh

notmuch new
notmuch tag -new +sent    -- tag:new folder:Sent
notmuch tag -new +private -- tag:new folder:Private
notmuch tag -new +junk    -- tag:new folder:Junk

notmuch search --format=json tag:tag | ~/.dotfiles/sbin/mail/new_popup
notmuch tag -new +inbox -- tag:new

# We're done, refresh the menubar
pkill -RTMIN+1 i3blocks
