#!/bin/bash

PW_DIR=~/Private/keys/password-store/
pwds="$(find "$PW_DIR" -name '*gpg' | sed "s#$PW_DIR##;s#\.gpg\$##")"
choice="$(printf "$pwds" | sort | dmenu -p 'password ' )"

if test -n "$choice"
then
    ~/.dotfiles/sbin/pass/pass-autotype "$choice" $*
else
    printf "Nothing choosen.\n" 1>&2
fi
