#!/bin/bash

level=$(amixer -D default sget Master | grep Mono | awk -F'[][]' '/on/ {print $2}' | grep .)
level=${level:0:-1}

if test "$level" -gt 70
then
    icon=
elif test "$level" -gt 40
then
    icon=
else
    icon=
fi

if grep -q '0x40: OUT$' "/proc/asound/card0/codec#0"
then
    echo "$icon $level%"
    echo "$icon"
else
    echo " $icon $level%"
    echo ""
fi
