#!/bin/bash

mode=$1

if test -z "$mode"
then
    exit 1
fi

# Rotate the touch screen control
if test "$mode" == "normal" || test "$mode" == "up"
then
    mode=normal
    xinput set-prop "ELAN Touchscreen" "Coordinate Transformation Matrix" \
        1 0 0 \
        0 1 0 \
        0 0 1
else
    case "$mode" in
        right)
            xinput set-prop "ELAN Touchscreen" "Coordinate Transformation Matrix" \
                0 1 0 \
               -1 0 1 \
                0 0 1
            ;;
        inverted|down)
            mode=inverted
            xinput set-prop "ELAN Touchscreen" "Coordinate Transformation Matrix" \
               -1 0 1 \
                0 -1 1 \
                0 0 1
            ;;
        left)
            xinput set-prop "ELAN Touchscreen" "Coordinate Transformation Matrix" \
                0 -1 1 \
                1 0 0 \
                0 0 1
            ;;
    esac
fi

# Actually do the flip of the screen
xrandr --output eDP1 --rotate $mode

