#!/bin/sh

# Set this to allow autotype to work correctly
setxkbmap gb

# Ask the user to mount the private directory
xfce4-terminal --fullscreen -x "/home/emily/.dotfiles/sbin/ui_mount"

# Check that the Private directory has been mounted before continuing
_path=$(realpath ~)
if ! mount | grep -q "^$_path/\.Private on $_path/Private type ecryptfs"
then
    exit 1
fi

#Tell i3blocks that private has been mounted
pkill -RTMIN+2 i3blocks

# Mount the connman settings
# As these contain wifi passwords etc, these are stored in my encrypted
# ~/Private/ directory rather than in plaintext.
mount /var/lib/connman
mount /var/lib/connman-vpn

# Now that connman has its settings, its safe to the daemon
sudo2 connmand

xfce4-terminal -T Mutt -x mutt

# Start the mail daemon
~/.dotfiles/sbin/mail/get_mail

#Tell i3blocks that private has been mounted
pkill -RTMIN+2 i3blocks
