#!/bin/sh

if ! test $UID -eq 0
then
    sudo $0 "$@"

    exit $?
fi

case $1 in
    connmand)
        shift
        connmand "$@"
        ;;
    pkg-db)
        pacman -Sy ;;
    mirrorlist)
        cd /etc/pacman.d
        test -e mirrorlist.new && \
        sed -r '/# (Worldwide|United Kingdom)/,/^$/s/^#([^#])/\1/' \
            mirrorlist.new > mirrorlist && \
        rm mirrorlist.new
esac
