#!/bin/sh

if ! test $UID -eq 0
then
    sudo $0 "$@"

    exit $?
fi

case $1 in
    connmand)
        shift
        connmand "$@"
        ;;
    pkg-db)
        yes | pacman -Syuw ;;
    mirrorlist)
        cd /etc/pacman.d
        test -e mirrorlist.pacnew && \
        sed -r '/# (Worldwide|United Kingdom)/,/^$/s/^#([^#])/\1/' \
            mirrorlist.pacnew > mirrorlist && \
        rm mirrorlist.pacnew
esac
