#!/bin/sh

AF=~/Private/conf/aliases
ME=~/Private/conf/me
tag=new
inbox=y
run_new=y
progress=

while test $# != 0
do
    case "$1" in
        --tag)
            shift
            tag=$1

            if test -z "$tag"
            then
                exit 1
            fi
            ;;
        --inbox)
            inbox=y ;;
        --no-inbox)
            inbox= ;;
        --run-new)
            run_new=y ;;
        --no-run-new)
            run_new= ;;
        --progress)
            progress=y ;;
        --no-progress)
            progress= ;;
    esac
    shift
done

get_header()
{
    echo $(grep -m1 -i "^$1:" $file | cut -f1 -d' ' --complement)
}

get_email()
{
    sed -r 's/.*<(.*)>.*/\1/'
}

progress()
{
    echo -ne "Running: [$i / $file_count]\r"
}

if [[ "$run_new" == y ]]
then
    notmuch new
fi

# Catch all the messages I have sent
notmuch tag -$tag +sent -- folder:Sent tag:new

# Google and Yahoo don't bounce me for no reason, so if I get a bounce
# from them I don't need to worry
notmuch tag -$tag +ignored -- from:MAILER-DAEMON@sweeb.net tag:new \(google or yahoo or gmail\)

if [[ "$progress" == y ]]
then
    file_count=$(notmuch count tag:$tag)
    i=0
    progress
fi

for file in $(notmuch search --output=files tag:$tag)
do
    msg_id=$(get_header 'Message-ID' | get_email)
    spam=$(get_header 'X-Spam-Status')
    from=$(get_header 'From')
    from_email=$(echo $from | get_email)
    to=$(get_header 'Delivered-To' | get_email)
    outcome=
    match=

    while read line
    do
        me_regex="$(echo $line | cut -f1 -d' ')"
        LEN=$(expr $(expr length $me_regex) + 1)
        ok_regex="${line:$LEN}"

        if test -z $(echo $to | grep -i "^$me_regex\$")
        then
            continue
        fi

        match=y

        if test -z "$ok_regex"
        then
            continue
        fi

        if test -z "$(echo $from_email | grep -i "^$ok_regex\$")"
        then
            outcome=fail
        else
            notmuch tag +to-closed -- id:$msg_id
            outcome=pass
            match=
            break
        fi
    done < $ME

    if [[ "$outcome" == "fail" ]]
    then
        notmuch tag +to-closed-bad -- id:$msg_id
    elif [[ "$match" == "y" ]]
    then
        notmuch tag +to-closed-new -- id:$msg_id
    fi

    # Check Junk
    if test "${spam:0:4}" == "Yes,"
    then
        notmuch tag +junk -- id:$msg_id
        continue
    fi

    name=$(grep -m1 -i "$from_email" $AF)

    # Unknown Sender
    if test -z "$name"
    then
        _name=$(echo $from | sed -r 's/.*"(.*)".*/\1/')

        if ! test -z "$_name"
        then
            name=$_name
        else
            name=$from
        fi
    # Known Sender with a defined nice name
    elif $(echo $name | grep -q '#')
    then
        name=$(echo $name | sed -r 's/^.*# *//')

        if test -z "$name"
        then
            notmuch tag +private -- id:$msg_id
            continue
        fi
    # Known Sender without a nice name (just use alias)
    else
        name=$(echo $name | cut -f2 -d' ')
        name=${name^}
    fi

    if [[ "$inbox" == y ]]
    then
        notify-send "New Mail From: $name" "$(get_header 'Subject')"
        notmuch tag +inbox -- id:$msg_id
    fi

    if [[ "$progress" == y ]]
    then
        i=$(expr $i + 1)
        progress
    fi
done

# We're done, refresh the menubar
if [[ "$inbox" == y ]]
then
    notmuch tag -$tag -- tag:$tag
fi
pkill -RTMIN+1 i3blocks
