#!/bin/sh
#
# Swaps the window currently in focused with the largest window on the
# current workspace.
#
set -e

# Filter command - this is the thing that does most of the leg work of
# finding the window we're going to swap with
FILTER="/home/emily/.dotfiles/scripts/filter.jq"

# Grab details about which workspace and output are currently in focus
active=$(swaymsg -t get_workspaces | \
    jq -r '.[] | select(.focused==true) | {output, name}')

# Grabs the id of the largest window
largestId=$(swaymsg -t get_tree | $FILTER --argjson active "$active")

# Instruct Sway to swap the currently focused window with the window id
# that we have located
swaymsg swap container with con_id $largestId

