#!/bin/zsh

# Exports
# ---------------------------------------------------------------------

# Vim stuff
export EDITOR=/usr/bin/vim

# Less stuff
export PAGER="less"
export LESS="-R"
export LESSHISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/lesshst"


# Using ZSH
# ---------------------------------------------------------------------

# General
setopt long_list_jobs
setopt interactivecomments
setopt multios

# Directory Changing
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus

# Dumb functions which zle apparently needs
function zle-line-init()
{
	echoti smkx
}

function zle-line-finish()
{
	echoti rmkx
}

autoload -U up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
zle -N zle-line-init
zle -N zle-line-finish

# History that doesn't suck
bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
bindkey "${terminfo[kcud1]}" down-line-or-beginning-search

# The default behaviour of delete is weird
bindkey "${terminfo[kdch1]}" delete-char


# History
# ---------------------------------------------------------------------

# Setup History
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify

# I have multiple terminals open at the same time, so sharing those
# commands is helpful
setopt share_history

# History variables
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zhistory"
HISTSIZE=10000
SAVEHIST=10000


# Aliases
# ---------------------------------------------------------------------

# Handy Shortcuts
alias c='git commit -S -m'
alias go='git push origin'
alias gh='git push github'
alias pp='git push origin && git push github'
alias p='ps aux | grep -v grep | grep'
alias l='ls -lah'
alias r='less -z56'
alias ss='ssh emily@emilyshepherd.me'
alias gc='ssh git@emilyshepherd.me'

# Run commands with colours by default
alias grep="grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}"
alias ls='ls --color=tty'

# Shortcut to become root
alias root='sudo SSH_CLIENT=$SSH_CLIENT su'


# Includes
# ---------------------------------------------------------------------
source ~/.dotfiles/zsh/completion.zsh
source ~/.dotfiles/zsh/termsupport.zsh
source ~/.dotfiles/zsh/prompt.zsh

autoload -U compinit
compinit -i -d "${XDG_CACHE_HOME:-$HOME/.cache}/zcompdump"
