#!/bin/zsh

# Init
# ---------------------------------------------------------------------

# Function to start the ssh agent and save the environment variables to
# home
function start_agent
{
    ssh-agent -t 600 > ~/.ssh_env
    source ~/.ssh_env > /dev/null
}

# Attempt to start the ssh agent
if ! [ -f ~/.ssh_env ]
then
	start_agent
else
    . ~/.ssh_env > /dev/null

    if ! ps -ef | grep -q "$SSH_AGENT_PID.*ssh-agent -t 600$"
	then
        start_agent
	fi
fi


# Annoying hack to Start X server because SystemD is a giant pain
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec xinit /bin/i3 -- /bin/X vt1


# Exports
# ---------------------------------------------------------------------

# General Path
export PATH="/bin:/bin/vendor_perl:/bin/core_perl"

# Let i3-sensible-terminal know which emulator we prefer
export TERMINAL="/bin/xfce4-terminal"

# Vim stuff
export EDITOR=/bin/vim

# Less stuff
export PAGER="less"
export LESS="-R"


# Using ZSH
# ---------------------------------------------------------------------

# General
setopt long_list_jobs
setopt interactivecomments
setopt multios

# Directory Changing
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus

# Dumb functions which zle apparently needs
function zle-line-init()
{
	echoti smkx
}

function zle-line-finish()
{
	echoti rmkx
}

autoload -U up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
zle -N zle-line-init
zle -N zle-line-finish

# History that doesn't suck
bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
bindkey "${terminfo[kcud1]}" down-line-or-beginning-search

# The default behaviour of delete is weird
bindkey "${terminfo[kdch1]}" delete-char


# History
# ---------------------------------------------------------------------

# Setup History
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify

# I have multiple terminals open at the same time, so sharing those
# commands is helpful
setopt share_history

# History variables
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000


# Aliases
# ---------------------------------------------------------------------

# Handy Shortcuts
alias c='git commit -S -m'
alias go='git push origin'
alias gh='git push github'
alias pp='git push origin && git push github'
alias p='ps aux | grep'
alias l='ls -lah'

# Run commands with colours by default
alias grep="grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}"
alias ls='ls --color=tty'

# Shortcut to become root
alias root='sudo SSH_CLIENT=$SSH_CLIENT su'


# Includes
# ---------------------------------------------------------------------
source ~/.dotfiles/zsh/completion.zsh
source ~/.dotfiles/zsh/termsupport.zsh
source ~/.dotfiles/zsh/prompt.zsh

autoload -U compinit
compinit -i
