#!/bin/sh

awk '
BEGIN {
    SIZES[0] = "k"
    SIZES[1] = "M"
    SIZES[2] = "G"
    SIZES[3] = "T"
}

/^Dirty:/ {
    mem  = $2
    size = 0
    while (mem >= 1024) {
        mem /= 1024
        size++
    }

    printf("%.1f%s\n", mem, SIZES[size])
}
' /proc/meminfo

