#!/bin/sh

DATA=${BLOCK_INSTANCE:-b}

if test $(expr $(datemath today - 071016) % 2) -eq 0
then
    case $DATA in
        a)
            echo "DOSAGE 150mg"
            echo "150"
            ;;
        b)
            echo "GEL LEFT"
            echo "L"
            ;;
    esac
else
    case $DATA in
        a)
            echo "DOSAGE 100mg"
            echo "100"
            ;;
        b)
            echo "GEL RIGHT"
            echo "R"
            ;;
    esac
fi
