#!/bin/sh

ID=${1:-$BLOCK_INSTANCE}

if test -z "$ID"
then
    echo "Usage: $0 <petition_id>"
    exit 1
fi

URL=https://petition.parliament.uk/petitions/$ID/count.json

printf "%'d" $(wget -q -O- $URL | egrep -o "[0-9]+")
