#!/bin/sh

ID=${1:-$BLOCK_INSTANCE}

if test -z "$ID"
then
    echo "Usage: $0 <petition_id>"
    exit 1
fi

COUNT_URL=https://petition.parliament.uk/petitions/$ID/count.json
MAP_URL="http://petitionmap.unboxedconsulting.com/?petition=$ID"

out=$(printf "%'d" $(wget -q -O- $COUNT_URL | egrep -o "[0-9]+"))

echo $out
echo $out

if test -n "$BLOCK_BUTTON"
then
    chromium $MAP_URL > /dev/null
    echo "#FFFF00"
fi

