#!/bin/sh

sudo2 pkg-db > /dev/null

if ! pacman -Qu > /dev/null
then
    echo 0
else
    pacman -Qu | wc -l
    
    ret=$(dunstify "Updates are availiable" "$(pacman -Qu)" -A y,Update)
    if test $ret == "y"
    then
        xfce4-terminal --drop-down -e \
            "bash -c 'sudo pacman -Su; pkill -RTMIN+3 i3blocks'"
    fi
fi
