#!/bin/bash

get()
{
    amixer sget $1 | grep -m1 "$2:" | awk -F'[][]' "/%/ {print \$$3}"
}

level=$(get Master Mono 2)
level=${level:0:-1}

if test "$(get Master Mono 6)" == "off"
then
    icon=
elif test "$(get Speaker Left 6)" == "off"
then
    icon=
elif test "$level" -gt 70
then
    icon=
elif test "$level" -gt 40
then
    icon=
else
    icon=
fi

echo "$icon $level%"
echo "$icon"

